### ISSUE TITLE
Multiple selection throws error

### ISSUE THREAD

**Issue by peeyushsahu** [neo4j-labs/neodash#787]
- NeoDash version: 2.4.2
- Neo4j Database version: 5.15.0 (Community).

Multiple selection throws an error if you removed all the selected values, also the refresh button does not work to refresh the widget.
- This happens after you initally added a selection and then remove it.

![image](https://github.com/neo4j-labs/neodash/assets/7063887/23bbc746-8d4f-4358-ad2e-efe22acf2e4b)

Error:
An unexpected error occurred. Try refreshing the component. 

TypeError: s.toLowerCase is not a function
    at http://localhost:35005/bundle.js:2:9596913
    at v (http://localhost:35005/bundle.js:2:9598851)
    at http://localhost:35005/bundle.js:2:9619699
    at ti (http://localhost:35005/bundle.js:152:1553619)
    at Ni (http://localhost:35005/bundle.js:152:1561763)
    at Hl (http://localhost:35005/bundle.js:152:1607754)
    at Ec (http://localhost:35005/bundle.js:152:1592991)
    at _c (http://localhost:35005/bundle.js:152:1592919)
    at wc (http://localhost:35005/bundle.js:152:1592782)
    at hc (http://localhost:35005/bundle.js:152:1589769)

**Comment by alfredorubin96** [comment]
Thank you for your feedback, it will be out in the next release.
